name: Image digest update

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest
    if: github.repository == 'chps-dev/chps-scorer'

    permissions:
      contents: read # the read the repo
      id-token: write # used to sign the commits using gitsign

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
      id: octo-sts
      with:
        scope: ${{ github.repository }}
        identity: digestabot

    - uses: chainguard-dev/digestabot@43222237fd8a07dc41a06ca13e931c95ce2cedac # v1.2.2
      with:
        token: ${{ steps.octo-sts.outputs.token }}
        author: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
        committer: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
        signoff: 'true'
        labels-for-pr: "automated pr"
        branch-for-pr: update-digests
        title-for-pr: Update images digests # optional
        description-for-pr: Update images digests
        commit-message: Update images digests
